-- AlterTable
ALTER TABLE `issuer` ADD COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `wallet_address` VARCHAR(191) NULL,
    ADD COLUMN `wallet_created_at` DATETIME(3) NULL;
